spring:
  application:
    name: GoalSyncBackend
  
  datasource:
    url: jdbc:h2:mem:goalsync_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8080

app:
  security:
    jwt:
      secret: "GoalSyncHackathonSuperSecretKeyForJwtGenerationDoNotShareInProduction12345"
      expirationMs: 86400000 # 24 hours
  ai:
    gemini:
      api-key: ${GEMINI_API_KEY:mock_key_for_hackathon}
